before_install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-embedded
# - sudo apt-get install -y qemu-system

script:
  - make PLATFORM=qemu
# - make PLATFORM=qemu --file tests/mutex_00/Makefile
