sudo: required

language: c

services:
  - docker

before_install:
  - docker pull bmarcot/vega-test
  - pip install --user cpp-coveralls

script:
  - ./configure --enable-gcov && make && make check
  - docker run --rm -v `pwd`:/vega -t bmarcot/vega-test python3 test/build.py

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'


branches:
  only:
    - master
    - /^devel([-\w]+)?$/
