sudo: required

services:
  - docker

before_install:
  - docker pull bmarcot/vega-test

script:
  - docker run --rm -v `pwd`:/vega -t bmarcot/vega-test python3 test/build.py

branches:
  only:
    - master
    - /^devel([-\w]+)?$/
