run: $(NAME).elf
	qemu-system-arm -serial stdio -nographic -cpu cortex-m3 -machine $(MACHINE) -kernel $^

run-with-semihosting: $(NAME).elf
	qemu-system-arm -semihosting -nographic -cpu cortex-m3 -machine $(MACHINE) -kernel $^
