

__SYSCALL_ARM(2, sched_yield)



__SYSCALL_ARM(6, pthread_mutex_lock)
__SYSCALL_ARM(7, pthread_mutex_unlock)
__SYSCALL_ARM(8, pthread_cond_signal)
__SYSCALL_ARM(9, pthread_cond_wait)
__SYSCALL_ARM(10, timer_create)
__SYSCALL_ARM(11, timer_settime)
__SYSCALL_ARM(12, timer_gettime)
__SYSCALL_ARM(13, msleep)
__SYSCALL_ARM(14, sysconf)
__SYSCALL_ARM(15, execve)
__SYSCALL_ARM(16, fork)
__SYSCALL_ARM(17, sigaction)
__SYSCALL_ARM(18, kill)
__SYSCALL_ARM(19, sigqueue)
__SYSCALL_ARM(20, open)
__SYSCALL_ARM(21, close)
__SYSCALL_ARM(22, read)
__SYSCALL_ARM(23, write)
__SYSCALL_ARM(24, lseek)
__SYSCALL_ARM(25, stat)
__SYSCALL_ARM(26, mount)
__SYSCALL_ARM(27, readdir_r)
__SYSCALL_ARM(28, getpid)
__SYSCALL_ARM(29, mmap)
__SYSCALL_ARM(30, munmap)
__SYSCALL_ARM(31, clone)
__SYSCALL_ARM(32, exit)
__SYSCALL_ARM(33, futex)
